from typing import List, Optional
from pydantic import BaseModel, Field

class Message(BaseModel):
    role: str = Field(..., description="Role of the message author, e.g. 'user' or 'assistant'")
    content: str = Field(..., description="Content of the message")

class Recommendation(BaseModel):
    name: str = Field(..., description="Name of the SHL assessment")
    url: str = Field(..., description="URL of the assessment in the catalog")
    test_type: str = Field(..., description="Category or type of the assessment")

class ChatRequest(BaseModel):
    messages: List[Message] = Field(..., description="Entire conversation history of messages")

class ChatResponse(BaseModel):
    reply: str = Field(..., description="Response text generated by the agent")
    recommendations: List[Recommendation] = Field(..., description="List of recommended assessments (0 to 10 items)")
    end_of_conversation: bool = Field(..., description="Flag indicating if the conversation has concluded")
    context: Optional[dict] = Field(default=None, description="Extracted hiring context state")
